version: '3'

tasks:

#####################################
### Composite Tasks and Shortcuts ###
#####################################

  pre-commit: 
    desc: Composite task to run all quick checks.
    cmds:
      - task unit
      - task lint-fix

  p:
    desc: Shortcut for `task pre-commit`.
    deps:
      - pre-commit

  ci-cd-checks:
    desc: Composite task to run all CI/CD checks.
    cmds:
      - task unit
      - task lint

######################
### Run Unit Tests ###
######################

  unit:
    desc: Run unit tests and check code coverage.
    cmds:
      # Recommended coverage viewer in VSCode: https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
      - poetry run pytest -s --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered --cov-fail-under=0 tests/unit/

  unit-watch:
    desc: Run unit tests and check code coverage immediately when files change.
    cmds:
      # Recommended coverage viewer in VSCode: https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters
      - poetry run ptw -- -s --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered --cov-fail-under=0 tests/unit/


###############################
### Code Quality Checks ###
###############################

  lint:
    desc: Lint the code without auto-fixing issues.
    cmds:
      - poetry run ruff check sec_ai/
      - poetry run mypy

  lint-fix:
    desc: Lint the code and auto-fix issues.
    cmds:
      - poetry run ruff check --fix sec_ai/
      - poetry run mypy
